name: drone-simulator
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  database:
    image: postgres:15.4
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=simulator
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: on-failure