module.exports = {
	importOrder: [
		'^@core/(.*)$',
		'^@server/(.*)$',
		'^@ui/(.*)$',
		'^\\$lib/components/(.*)$',
		'^\\$lib/(.*)$',
		'^[./]',
	],
	arrowParens: 'always',
	bracketSameLine: true,
	bracketSpacing: true,
	importOrderSeparation: true,
	importOrderSortSpecifiers: true,
	printWidth: 80,
	proseWrap: 'always',
	semi: true,
	singleQuote: true,
	tabWidth: 2,
	trailingComma: 'all',
	useTabs: true,
};